name: csn_flutter_example
description: Example app for csn_flutter
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  csn_flutter:
    path: ..
  flutter_webrtc: 1.2.1
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.15.1
  firebase_messaging: ^15.1.6

dependency_overrides:
  webrtc_interface: 1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
