name: csn_flutter
version: 0.3.1
description: Flutter SDK for CSN realtime audio/video calling with prebuilt request-queue and call UI.
repository:  https://github.com/SanketKudale/InfiMeetFlutter
homepage:  https://github.com/SanketKudale/InfiMeetFlutter
issue_tracker:  https://github.com/SanketKudale/InfiMeetFlutter/issues
topics:
  - webrtc
  - video-calling
  - signaling
  - realtime

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^2.4.0
  flutter_webrtc: ^1.2.1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
