name: csn_flutter
version: 0.1.0
description: Flutter SDK for CSN audio/video calling backend.
repository: https://example.com/csn_flutter
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^2.4.0
  flutter_webrtc: 1.2.1

dependency_overrides:
  webrtc_interface: 1.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
